import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Home1</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/contactus">Contactus</Link>
        </li>
        <li>
          <Link to="/commercialsectors">CommercialSectors</Link>
        </li>
        <li>
          <Link to="/residentialsectors">ResidentialSectors</Link>
        </li>
        <li>
          <Link to="/visitormanagementsystem">Visitormanagementsystem</Link>
        </li>
        <li>
          <Link to="/blogs">Blogs</Link>
        </li>
        <li>
          <Link to="/blogdetails">Blogdetails</Link>
        </li>
        <li>
          <Link to="/privacypolicy">Privacypolicy</Link>
        </li>
        <li>
          <Link to="/termsofuse">Termsofuse</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/teammember">Teammember</Link>
        </li>
        <li>
          <Link to="/newsletter">Newsletter</Link>
        </li>
        <li>
          <Link to="/messages">Messages</Link>
        </li>
        <li>
          <Link to="/controljob">Controljob</Link>
        </li>
        <li>
          <Link to="/services">Services</Link>
        </li>
        <li>
          <Link to="/feature">Feature</Link>
        </li>
        <li>
          <Link to="/aboutusone">AboutusOne</Link>
        </li>
        <li>
          <Link to="/partners">Partners</Link>
        </li>
        <li>
          <Link to="/forgotyourpasswordone">ForgotyourpasswordOne</Link>
        </li>
        <li>
          <Link to="/addnewteammember">AddNewTeamMember</Link>
        </li>
        <li>
          <Link to="/newnewsletter">Newnewsletter</Link>
        </li>
        <li>
          <Link to="/replay">Replay</Link>
        </li>
        <li>
          <Link to="/addnewjob">Addnewjob</Link>
        </li>
        <li>
          <Link to="/addnewservice">Addnewservice</Link>
        </li>
        <li>
          <Link to="/addnewfeature">Addnewfeature</Link>
        </li>
        <li>
          <Link to="/newpartner">NewPartner</Link>
        </li>
        <li>
          <Link to="/forgotyourpassword">Forgotyourpassword</Link>
        </li>
        <li>
          <Link to="/editteammember">EditTeamMember</Link>
        </li>
        <li>
          <Link to="/addnewsubscription">AddNewSubscription</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/editjob">Editjob</Link>
        </li>
        <li>
          <Link to="/editservice">Editservice</Link>
        </li>
        <li>
          <Link to="/editfeature">Editfeature</Link>
        </li>
        <li>
          <Link to="/editpartner">EditPartner</Link>
        </li>
        <li>
          <Link to="/editvalues">EditValues</Link>
        </li>
        <li>
          <Link to="/newpassword">Newpassword</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
